import '@testing-library/jest-dom';

// Mock chrome API for tests
const mockChrome = {
  runtime: {
    getManifest: () => ({ version: '0.6.1' }),
    sendMessage: vi.fn().mockResolvedValue({ success: true, data: 'test' }),
  },
  storage: {
    local: {
      get: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({}),
    },
  },
};

// Define chrome in the global scope for tests
global.chrome = mockChrome as any;

// Mock data-base64 imports
vi.mock('data-base64:../assets/icon.png', () => ({
  default: 'mock-icon-data',
}));

// Mock data-text imports
vi.mock('data-text:./locales/zh-CN/CHANGELOG.md', () => 'Chinese Changelog Content');
vi.mock('data-text:./locales/en-US/CHANGELOG.md', () => 'English Changelog Content');

// Mock I18nService
vi.mock('~services/I18nService', () => ({
  I18nService: {
    t: (key: string) => {
      const translations: Record<string, string> = {
        'settings_general': '通用设置',
        'settings_zhihu': '知乎设置',
        'settings_reddit': 'Reddit设置',
        'settings_history': '历史记录',
        'settings_debug': '调试设置',
        'version_info': '版本信息',
        'current_version': '当前版本',
        'changelog': '更新日志',
        'version_history': '版本历史',
        'plugin_enabled': '插件已启用',
        'plugin_disabled': '插件已禁用',
        'plugin_enabled_desc': '插件将在支持的页面上运行',
        'plugin_disabled_desc': '插件将不会在任何页面上运行',
        'ai_provider': 'AI提供商',
        'api_key': 'API密钥',
        'api_base_url': 'API基础URL',
        'model_select': '选择模型',
        'test_connection': '测试连接',
        'connection_success': '连接成功',
        'connection_failed': '连接失败',
        'saved': '已保存',
        'loading': '加载中...',
        'confirm_delete': '确定要删除吗？',
        'confirm_clear_all': '确定要清除所有记录吗？',
        'clear_all': '清除所有',
        'history_empty': '暂无历史记录',
        'export_markdown': '导出Markdown',
        'export_image': '导出图片',
        'delete': '删除',
        'unknown_user': '未知用户',
        'topic_classification': '话题分类',
        'ai_summary': 'AI摘要',
        'value_orientation': '价值观倾向',
        'mode_fast': '快速',
        'mode_balanced': '平衡',
        'mode_deep': '深度',
        'mode_fast_desc': '最少内容，最快分析',
        'mode_balanced_desc': '适中内容，平衡速度与质量',
        'mode_deep_desc': '最多内容，最全面分析',
        'analyze_limit': '分析限制',
        'debug_mode': '调试模式',
        'debug_mode_desc': '启用详细日志记录',
        'saved_successfully': '保存成功',
        'export_image_failed': '图片导出失败',
        'app_description': 'AI驱动的用户画像分析',
        'settings': '设置',
        'app_name': 'DeepProfile',
        'save': '保存',
        'cancel': '取消',
        'analyzing': '分析中',
        'wait_moment': '请稍候',
        'evidence': '证据',
        'debug_info': '调试信息',
        'expand': '展开',
        'collapse': '收起',
        'source': '来源',
        'reanalyze': '重新分析',
        'history_record': '历史记录',
        'error_401': '未授权错误',
        'error_402': '支付必需错误',
        'error_404': '未找到错误',
        'error_429': '请求过多错误',
        'error_500': '服务器错误',
        'error_network': '网络错误',
        'error_zhihu_403': '知乎访问被拒绝',
        'error_user_not_found': '用户未找到',
        'category_politics': '政治',
        'category_economy': '经济',
        'category_society': '社会',
        'category_technology': '科技',
        'category_culture': '文化',
        'category_environment': '环境',
        'category_entertainment': '娱乐',
        'category_lifestyle_career': '生活职业',
        'category_general': '综合',
        'ai_summary': 'AI摘要',
        'topic_classification': '话题分类',
        
        // Comment Analysis
        'comment_summary_btn': '分析评论',
        'analyzing_comments': '正在分析当前页面的评论...',
        'expanding_comments': '正在展开评论区...',
        'extracting_comments': '正在提取评论数据...',
        'anonymous_user': '匿名用户',
        'not_enough_comments': '评论数量不足以进行分析',
        'comment_analysis_instruction': '，请尝试增加显示的评论数量。',
        'ai_reading': 'AI 正在阅读大家的观点...',
        'comment_analysis_summary': '评论分析总结',
        'comment_analysis_ai_generated': 'AI 生成',
        'sentiment_support': '支持',
        'sentiment_neutral': '中立',
        'sentiment_oppose': '反对',
        'expand_key_points': '展开要点',
        'collapse_key_points': '收起要点',
        'deep_insight': '深度洞察',
        'logic_fallacy': '检测到逻辑谬误',
        'unknown_type': '未知类型',
        'example_quote': '示例引用',
        'comment_analysis_failed': '分析失败',
        
        // Reddit Overlay
        'deep_profile_analysis': '深度画像分析',
        
        // Additional keys
        'total_users_max': '总计 {count} 用户 (最大 {max})',
      };
      return translations[key] || key;
    },
    init: vi.fn(),
    setLanguage: vi.fn(),
    getLanguage: () => 'zh-CN',
  }
}));

// Mock the locale modules
vi.mock('~locales/zh-CN', async () => ({
  zhCN: {
    app_name: 'DeepProfile',
    app_description: 'AI驱动的用户画像分析',
    settings: '设置',
    settings_general: '通用设置',
    settings_zhihu: '知乎设置',
    settings_reddit: 'Reddit设置',
    settings_history: '历史记录',
    settings_debug: '调试设置',
    version_info: '版本信息',
    current_version: '当前版本',
    changelog: '更新日志',
    version_history: '版本历史',
    plugin_enabled: '插件已启用',
    plugin_disabled: '插件已禁用',
    plugin_enabled_desc: '插件将在支持的页面上运行',
    plugin_disabled_desc: '插件将不会在任何页面上运行',
    ai_provider: 'AI提供商',
    api_key: 'API密钥',
    api_base_url: 'API基础URL',
    model_select: '选择模型',
    test_connection: '测试连接',
    connection_success: '连接成功',
    connection_failed: '连接失败',
    saved: '已保存',
    loading: '加载中...',
    confirm_delete: '确定要删除吗？',
    confirm_clear_all: '确定要清除所有记录吗？',
    clear_all: '清除所有',
    history_empty: '暂无历史记录',
    export_markdown: '导出Markdown',
    export_image: '导出图片',
    delete: '删除',
    unknown_user: '未知用户',
    topic_classification: '话题分类',
    ai_summary: 'AI摘要',
    value_orientation: '价值观倾向',
    mode_fast: '快速',
    mode_balanced: '平衡',
    mode_deep: '深度',
    mode_fast_desc: '最少内容，最快分析',
    mode_balanced_desc: '适中内容，平衡速度与质量',
    mode_deep_desc: '最多内容，最全面分析',
    analyze_limit: '分析限制',
    debug_mode: '调试模式',
    debug_mode_desc: '启用详细日志记录',
    saved_successfully: '保存成功',
    export_image_failed: '图片导出失败',
    topic_classification: '话题分类',
  }
}));

vi.mock('~locales/en-US', async () => ({
  enUS: {
    app_name: 'DeepProfile',
    app_description: 'AI-powered User Profile Analysis',
    settings: 'Settings',
    settings_general: 'General Settings',
    settings_zhihu: 'Zhihu Settings',
    settings_reddit: 'Reddit Settings',
    settings_history: 'History',
    settings_debug: 'Debug Settings',
    version_info: 'Version Info',
    current_version: 'Current Version',
    changelog: 'Changelog',
    version_history: 'Version History',
    plugin_enabled: 'Plugin Enabled',
    plugin_disabled: 'Plugin Disabled',
    plugin_enabled_desc: 'Plugin will run on supported pages',
    plugin_disabled_desc: 'Plugin will not run on any pages',
    ai_provider: 'AI Provider',
    api_key: 'API Key',
    api_base_url: 'API Base URL',
    model_select: 'Select Model',
    test_connection: 'Test Connection',
    connection_success: 'Connection Successful',
    connection_failed: 'Connection Failed',
    saved: 'Saved',
    loading: 'Loading...',
    confirm_delete: 'Are you sure you want to delete?',
    confirm_clear_all: 'Are you sure you want to clear all records?',
    clear_all: 'Clear All',
    history_empty: 'No history records',
    export_markdown: 'Export Markdown',
    export_image: 'Export Image',
    delete: 'Delete',
    unknown_user: 'Unknown User',
    topic_classification: 'Topic Classification',
    ai_summary: 'AI Summary',
    value_orientation: 'Value Orientation',
    mode_fast: 'Fast',
    mode_balanced: 'Balanced',
    mode_deep: 'Deep',
    mode_fast_desc: 'Minimum content, fastest analysis',
    mode_balanced_desc: 'Moderate content, balanced speed and quality',
    mode_deep_desc: 'Maximum content, most comprehensive analysis',
    analyze_limit: 'Analyze Limit',
    debug_mode: 'Debug Mode',
    debug_mode_desc: 'Enable detailed logging',
    saved_successfully: 'Saved Successfully',
    export_image_failed: 'Image Export Failed',
    topic_classification: 'Topic Classification',
  }
}));

