import { TopicService, type MacroCategory } from "./TopicService";
import { calculateFinalLabel } from "./LabelUtils";
import type { ProfileData } from "~types";

export class ExportService {
  
  /**
   * 将画像数据转换为 Markdown 格式
   */
  static toMarkdown(profile: ProfileData, category: MacroCategory, url: string, generatedAt: number): string {
    const categoryName = TopicService.getCategoryName(category);
    const genDate = new Date(generatedAt).toLocaleString('zh-CN');
    const expDate = new Date().toLocaleString('zh-CN');
    
    let md = `# 👤 DeepProfile 用户画像分析报告\n\n`;
    md += `> **用户昵称**: ${profile.nickname || '未知用户'}\n`;
    md += `> **分析领域**: ${categoryName}\n`;
    md += `> **生成时间**: ${genDate}\n`;
    md += `> **导出时间**: ${expDate}\n`;
    md += `> **原文链接**: [点击跳转](${url})\n\n`;
    
    md += `## 📝 核心总结\n\n${profile.summary}\n\n`;
    
    md += `## 🧭 价值取向\n\n`;
    if (profile.value_orientation && profile.value_orientation.length > 0) {
      md += `| 维度 | 倾向 | 强度 |\n`;
      md += `| :--- | :--- | :--- |\n`;
      
      profile.value_orientation.forEach(item => {
        const { label, percentage } = calculateFinalLabel(item.label, item.score);
        const bar = this.generateProgressBar(percentage, item.score);
        md += `| ${label} | ${bar} | ${percentage}% |\n`;
      });
      md += `\n`;
    } else {
      md += `*暂无明显的价值取向数据*\n\n`;
    }
    
    if (profile.evidence && profile.evidence.length > 0) {
      md += `## 🔍 关键证据\n\n`;
      profile.evidence.forEach((ev, index) => {
        md += `### ${index + 1}. ${ev.analysis}\n`;
        md += `> "${ev.quote}"\n`;
        if (ev.source_title) {
          md += `> — 来自: *${ev.source_title}*\n`;
        }
        md += `\n`;
      });
    }
    
    md += `---\n*Generated by DeepProfile Chrome Extension*`;
    
    return md;
  }

  private static generateProgressBar(percentage: number, score: number): string {
    const blocks = Math.round(percentage / 10);
    const filled = score > 0 ? '🟦' : '🟥';
    return filled.repeat(blocks) + '⬜'.repeat(10 - blocks);
  }
}
