import { TopicService, type MacroCategory } from "./TopicService";
import { calculateFinalLabel } from "./LabelUtils";
import type { ProfileData } from "~types";

export class ExportService {
  
  /**
   * 将画像数据转换为 Markdown 格式
   */
  static toMarkdown(profile: ProfileData, category: MacroCategory, url: string): string {
    const categoryName = TopicService.getCategoryName(category);
    const date = new Date().toLocaleDateString();
    
    let md = `# 👤 DeepProfile 用户画像分析报告\n\n`;
    md += `> **用户昵称**: ${profile.nickname || '未知用户'}\n`;
    md += `> **分析领域**: ${categoryName}\n`;
    md += `> **生成日期**: ${date}\n`;
    md += `> **原文链接**: [点击跳转](${url})\n\n`;
    
    md += `## 📝 核心总结\n\n${profile.summary}\n\n`;
    
    md += `## 🧭 价值取向\n\n`;
    if (profile.value_orientation && profile.value_orientation.length > 0) {
      md += `| 维度 | 倾向 | 强度 |\n`;
      md += `| :--- | :--- | :--- |\n`;
      
      profile.value_orientation.forEach(item => {
        const { label, percentage } = calculateFinalLabel(item.label, item.score);
        const bar = this.generateProgressBar(percentage, item.score);
        md += `| ${label} | ${bar} | ${percentage}% |\n`;
      });
      md += `\n`;
    } else {
      md += `*暂无明显的价值取向数据*\n\n`;
    }
    
    if (profile.evidence && profile.evidence.length > 0) {
      md += `## 🔍 关键证据\n\n`;
      profile.evidence.forEach((ev, index) => {
        md += `### ${index + 1}. ${ev.analysis}\n`;
        md += `> "${ev.quote}"\n`;
        if (ev.source_title) {
          md += `> — 来自: *${ev.source_title}*\n`;
        }
        md += `\n`;
      });
    }
    
    md += `---\n*Generated by DeepProfile Chrome Extension*`;
    
    return md;
  }

  private static generateProgressBar(percentage: number, score: number): string {
    const blocks = Math.round(percentage / 10);
    const filled = score > 0 ? '🟦' : '🟥';
    return filled.repeat(blocks) + '⬜'.repeat(10 - blocks);
  }

  /**
   * 生成图片分享卡片 (HTML Canvas)
   * 注意：此方法返回一个 Promise，解析为图片的 Data URL
   */
  static async toImage(profile: ProfileData, category: MacroCategory): Promise<string> {
    // 由于在 Service Worker 或非 DOM 环境中无法直接操作 Canvas，
    // 此逻辑通常需要在 Content Script 或 Popup/Options 页面中运行。
    // 这里我们返回一个可以在前端渲染的 HTML 结构数据，或者如果环境允许直接绘图。
    // 为了简化，我们假设这个方法会被前端组件调用，我们提供绘图逻辑。
    
    // 实际的绘图逻辑将由前端组件实现，这里我们只提供数据准备
    // 或者我们可以使用 OffscreenCanvas (如果浏览器支持)
    
    throw new Error("Image generation should be handled in the UI component using html2canvas or similar libraries.");
  }
}
