import type { LocaleDict } from "./index";

export const enUS: LocaleDict = {
  // General
  app_name: "DeepProfile",
  app_description: "AI-powered User Profile Analysis Tool",
  loading: "Loading...",
  save: "Settings Saved",
  saved: "Saved!",
  cancel: "Cancel",
  delete: "Delete",
  confirm_delete: "Are you sure?",
  clear_all: "Clear All",
  confirm_clear_all: "Are you sure you want to clear all history? This action cannot be undone.",
  export_markdown: "Export as Markdown",
  export_image: "Export as Image",
  export_image_failed: "Export as Image Failed",
  settings: "Settings Menu",

  // Options Page
  settings_general: "General Settings",
  settings_zhihu: "Zhihu Settings",
  settings_reddit: "Reddit Settings",
  settings_twitter: "Twitter Settings",
  settings_quora: "Quora Settings",
  debug_mode: "Debug Mode",
  debug_mode_desc: "Enable detailed logging",
  settings_history: "History",
  settings_debug: "Developer Options",
  plugin_enabled: "✅ Plugin Enabled",
  plugin_disabled: "⛔ Plugin Disabled",
  plugin_enabled_desc: "DeepProfile is working normally and will display analysis buttons on target websites.",
  plugin_disabled_desc: "DeepProfile is completely turned off and will not inject code into any website.",
  ai_provider: "AI Provider",
  api_key: "API Key",
  api_base_url: "API Base URL",
  model_select: "Model Selection",
  test_connection: "🔌 Test Connection",
  connection_success: "✅ Connection Successful",
  connection_failed: "❌ Connection Failed",
  analysis_mode: "Analysis Mode",
  analyze_limit: "Number of Answers to Analyze",
  mode_fast: "⚡ Fast",
  mode_balanced: "⚖️ Balanced",
  mode_deep: "🧠 Deep",
  mode_fast_desc: "Minimal content, fastest analysis",
  mode_balanced_desc: "Moderate content, balanced speed and quality",
  mode_deep_desc: "Maximum content, most comprehensive analysis",
  
  // Categories
  category_politics: "🏛️ Politics",
  category_economy: "💰 Economy",
  category_society: "👥 Society",
  category_technology: "💻 Technology",
  category_culture: "🎨 Culture",
  category_environment: "🌍 Environment",
  category_entertainment: "🎮 Entertainment",
  category_lifestyle_career: "💼 Lifestyle & Career",
  category_general: "🌐 General",
  
  // Profile Card
  analyzing: "Analyzing",
  topic_classification: "Topic Classification",
  value_orientation: "Value Orientation",
  ai_summary: "AI Summary",
  evidence: "Evidence",
  source: "Source",
  expand: "Expand",
  collapse: "Collapse",
  reanalyze: "Re-analyze",
  wait_moment: "Please wait a moment...",
  history_record: "History Record",
  history_empty: "No history records",
  total_users_max: "Total {count} users (Max {max})",
  debug_info: "Debug Info",
  token_usage: "Model",
  total_duration: "Total Duration",
  llm_duration: "AI Duration",
  data_items: "Data Items",
  data_breakdown: "Data Breakdown",
  unknown_user: "Unknown User",
  unknown_topic: "Unknown Topic",
  
  // Errors
  error_401: "Authentication Failed (401) 🔐: Please check if your API Key is correct.",
  error_402: "Insufficient Balance (402) 💸: Please check your API Key balance.",
  error_404: "Model Not Found (404) 🗺️: Please check your model configuration.",
  error_429: "Too Many Requests (429) 🔥: AI is busy, please try again later.",
  error_500: "AI Provider Error (500) 💥: Please try again later.",
  error_network: "Network Error 🌐: Please check your internet connection or proxy settings.",
  error_zhihu_403: "Access Denied by Zhihu (403) 🚧. Please try refreshing the page or logging in.",
  error_user_not_found: "User data not found 🕵️‍♂️. The account might be banned or set to private.",
  error_extension_context: "Extension context invalidated. Please refresh the page to retry.",
  error_content_filter: "Content Safety Review Failed: The input content was flagged by the AI provider as potentially inappropriate. Please try switching to a different model like DeepSeek or OpenAI.",

  // Export
  click_jump: "Click to Jump",
  no_data: "No data available",
  generated_by: "Generated by",
  scan_to_install: "Scan to install",
  start_ai_journey: "Start your AI journey",
  ai_profile_analysis: "AI-powered User Profile Analysis",
  date_label: "Date",
  
  // Comment Analysis
  analyzing_comments: "Analyzing comments on current page...",
  expanding_comments: "Expanding comment section...",
  extracting_comments: "Extracting comment data...",
  ai_reading: "AI is reading everyone's opinions...",
  comment_analysis_failed: "Analysis failed",

  // Theme Settings
  theme_settings: "Theme Settings",
  select_theme: "Select Theme",
  create_custom_theme: "Create Custom Theme",
  theme_id: "Theme ID",
  theme_name: "Theme Name",
  theme_description: "Theme Description",
  unique_theme_identifier: "Unique theme identifier",
  display_name_for_theme: "Display name for the theme",
  optional_description: "Optional description for the theme",
  create_theme: "Create Theme",
  theme_created: "Theme created successfully!",
  theme_updated: "Theme updated successfully!",
  theme_deleted: "Theme deleted successfully!",
  theme_applied: "Theme applied successfully!",
  theme_zhihu_white_name: "Zhihu White Theme",
  theme_zhihu_white_desc: "Zhihu-inspired light theme with blue accents",
  theme_zhihu_black_name: "Zhihu Dark Theme",
  theme_zhihu_black_desc: "Zhihu-inspired dark theme with blue accents",
  theme_reddit_white_name: "Reddit White Theme",
  theme_reddit_white_desc: "Reddit-inspired light theme with orange-blue accents",
  theme_reddit_black_name: "Reddit Dark Theme",
  theme_reddit_black_desc: "Reddit-inspired dark theme with orange-blue accents",
  failed_load_themes: "Failed to load themes",
  failed_apply_theme: "Failed to apply theme",
  failed_create_theme: "Failed to create theme",
  failed_delete_theme: "Failed to delete theme",
  failed_save_theme: "Failed to save theme",
  theme_id_name_required: "Please enter theme ID and name",
  cannot_delete_builtin_theme: "Cannot delete built-in themes",
  confirm_delete_theme: "Are you sure you want to delete this theme? This action cannot be undone.",
  edit: "Edit",
  color_settings: "Color Settings",
  color_primary: "Primary Color",
  color_secondary: "Secondary Color",
  color_background: "Background Color",
  color_surface: "Surface Color",
  color_text: "Text Color",
  color_textSecondary: "Secondary Text Color",
  color_border: "Border Color",
  color_success: "Success Color",
  color_warning: "Warning Color",
  color_error: "Error Color",
  color_accent: "Accent Color",
  save_changes: "Save Changes",
  
  // Context Invalidated Error
  extension_context_invalidated: "Extension context invalidated",
  extension_context_invalidated_title: "Extension Context Invalidated",
  extension_context_invalidated_desc: "Extension context has been invalidated. Please refresh the page to retry.",
  
  // Version Info
  version_info: "Version Information",
  current_version: "Current Version",
  changelog: "Changelog",
  version_history: "Version History",
  
  // Comment Analysis
  comment_summary_btn: "Analyze Comments",
  anonymous_user: "Anonymous User",
  not_enough_comments: "Not enough comments for analysis",
  comment_analysis_instruction: ", please try increasing the number of comments displayed.",
  comment_analysis_summary: "Comment Analysis Summary",
  comment_analysis_ai_generated: "AI Generated",
  sentiment_support: "Support",
  sentiment_neutral: "Neutral",
  sentiment_oppose: "Oppose",
  expand_key_points: "Expand Key Points",
  collapse_key_points: "Collapse Key Points",
  deep_insight: "Deep Insight",
  logic_fallacy: "Logical Fallacy Detected",
  unknown_type: "Unknown Type",
  example_quote: "Example Quote",
  
  // Reddit Overlay
  deep_profile_analysis: "Deep Profile Analysis",

  // Progress Messages
  reading_user_profile: "Reading user profile",
  reading_content: "Reading user content",
  ai_analyzing: "AI is analyzing"
};

// DeepProfile Current Version Changelog
export const enUSChangelog = `# DeepProfile Current Version Changelog

## Current Version: v0.8.1 (Beta) - Memory Optimization & Leak Fixes

### 🚀 Memory Optimization (v0.8.1)
- **Memory Leak Fixes**: Fixed memory leaks caused by timers not being properly cleared in the background service
- **Event Listener Management**: Improved registration and deregistration mechanisms for event listeners in content scripts to prevent duplicate bindings
- **Cache Strategy Optimization**: Optimized cache cleanup mechanisms for history records, regularly cleaning up expired data
- **Component Unmount Optimization**: Improved unmount logic for React components to ensure DOM nodes and event handlers are properly cleaned up
- **Resource Management**: Added tracking for active timers to prevent timer accumulation

### Core Feature (v0.8.0) - Platform Expansion & UI Modernization
- ✅ **Quora Platform Support**: Added user profile analysis support for Quora platform, including content scraping and user info extraction
- ✅ **Twitter/X Platform Support**: Added user profile analysis support for Twitter/X platform, adapting to new API interfaces
- ✅ **UI Modernization**: Adopted modern UI design, updated settings page layout with card-based design for improved visual experience
- ✅ **Icon Updates**: Added dedicated icons for all supported platforms, enhancing interface aesthetics
- ✅ **Responsive Enhancement**: Optimized interface display across different screen sizes

### Core Feature (v0.7.1) - Label Display & LLM Output Optimization
- ✅ **Label Display Fix**: Resolved issues where certain labels (e.g., \`competition_vs_equality\`, \`speculation_vs_value\`) were not displaying correctly in the frontend.
- ✅ **Label Definition Sync**: Ensured label definitions in \`LabelService\` are fully synchronized with \`LabelDefinitions\`, eliminating display errors caused by ID mismatches.
- ✅ **LLM Output Standardization**: Added automatic standardization for LLM-returned label IDs, capable of correcting non-standard label IDs (e.g., mapping \`nationalism_globalism\` to \`geopolitics\`).
- ✅ **Duplicate Label Handling**: Optimized result parsing logic to automatically merge and deduplicate labels returned by LLM, prioritizing scores with higher confidence.

### Core Feature (v0.7.0) - Improved Profile Analysis Accuracy & Consistency
- ✅ **AI Summary Consistency**: Ensure AI-generated summaries are consistent with numerical label scores
- ✅ **Consistency Verification Mechanism**: Added ConsistencyService to verify and fix summary-label consistency
- ✅ **Label-Summary Association**: High-scoring labels are clearly reflected in summaries
- ✅ **Evidence Support**: Ensure analysis evidence matches label scores

### Core Feature (v0.6.3) - Analysis Progress Visualization & Label Display Optimization
- ✅ **Progress Estimation**: Show estimated remaining time based on analysis mode (e.g., "Analyzing... (15s)")
- ✅ **Progress Bar Animation**: Display dynamic progress bar for intuitive analysis progress indication.
- ✅ **Mode Differentiation**: Different analysis modes (Fast/Balanced/Deep) show different estimated times.
- ✅ **Bidirectional Divergent Bar Chart Optimization**: Value labels are left-right aligned, with percentages displayed above bidirectional divergent bars.

### v0.6.2 (2024-01-09) - Theme System
*   **Feature**: **Theme Customization**, supports user-defined appearance themes, including color schemes, fonts, sizes, etc.
*   **Feature**: **Multiple Built-in Themes**, provides multiple preset themes, including Zhihu White/Black themes, Reddit White/Black themes.
*   **Feature**: **Dynamic Theme Switching**, supports real-time theme switching without refreshing the page.
*   **Feature**: **CSS Variable Driven**, uses CSS variables to implement global theme dynamic application, ensuring all components update synchronously.
*   **Feature**: **Theme Management**, supports creating, editing, deleting custom themes, and provides theme import/export functionality.

### v0.6.1 (2024-01-09) - Real-time Settings Save
*   **Feature**: Implemented **real-time settings save functionality** on the settings page, all configuration changes are immediately saved to storage automatically.
*   **Feature**: Removed manual save button, simplifying the settings interface.
*   **Feature**: Configuration changes take effect immediately without restart or refresh.
*   **UX**: Improved user experience with a smoother settings workflow.

### v0.6.0 (2024-01-08) - Reddit Platform Multilingual Support Enhancement
*   **Feature**: Fixed I18nService initialization issue on Reddit platform to ensure multilingual functionality works properly.
*   **Feature**: Refactored button injection logic on Reddit platform to align with Zhihu platform, resolving the disappearing button issue.
*   **Feature**: Ensured that Reddit platform analysis buttons and user profile cards support Chinese/English interface switching.
*   **Feature**: Implemented consistent button injection mechanism aligned with Zhihu platform, including configuration checks, cleanup functions, and orphaned button removal features.
*   **Feature**: Updated internationalization support for loading, analysis, and error status messages to ensure interface fully follows user language settings.

### v0.5.0 (2024-01-07) - Reddit Platform Support
*   **Feature**: **Reddit Platform Support**, added support for analyzing Reddit user profiles.
*   **Feature**: **Cross-Platform Architecture**, refactored code to support multi-social platform expansion.
*   **Feature**: **Platform-Specific Configuration**, allows setting different analysis parameters for different platforms.
*   **Feature**: **Reddit Content Scraping**, implemented content extraction and parsing for Reddit API.
*   **Feature**: **Platform-Specific UI**, adapted user interface styles for Reddit.

### v0.4.0 (2024-01-06) - Comment Analysis Feature
*   **Feature**: **Comment Analysis**, added specialized comment analysis feature to analyze user comments under specific posts.
*   **Feature**: **Sentiment Analysis**, implemented emotional tendency analysis of user comments (support/oppose/neutral).
*   **Feature**: **Opinion Clustering**, automatically clusters main opinions in user comments.
*   **Feature**: **Position Identification**, identifies user positions on controversial topics.
*   **Feature**: **Public Opinion Overview**, generates AI summary of overall public opinion.

### v0.3.0 (2024-01-05) - Value Label System
*   **Feature**: **Value Label System**, established multi-dimensional value orientation label system (political, economic, social, cultural, technological, etc.).
*   **Feature**: **Quantitative Analysis**, transforms value orientations into quantitative scores between -1 and 1.
*   **Feature**: **Bipolar Coordinates**, uses bipolar coordinate system to intuitively display value orientations.
*   **Feature**: **Label Visualization**, displays value distributions in various dimensions through chart form.
*   **Feature**: **Label Explanations**, provides detailed explanations for each label.

### v0.2.1 (2024-01-04) - Optimization & Fixes
*   **Fix**: Optimized content scraping logic, added handling for API rate limiting.
*   **Fix**: Fixed issues where analysis results were incomplete in certain situations.
*   **Fix**: Improved error handling mechanisms, providing clearer error messages.
*   **UI**: Fine-tuned UI component styles, enhancing visual effects.
*   **Performance**: Optimized caching mechanisms, improving response speed for repeated queries.

### v0.2.0 (2024-01-03) - Deep Analysis and Context Awareness
*   **Feature**: Added context-aware functionality, automatically filtering user's relevant answers based on current browsing question.
*   **Feature**: Added "Analysis Mode" setting (Fast/Balanced/Deep), Deep mode supports irony identification.
*   **Feature**: Profile labels added confidence probability display.
*   **Feature**: Enhanced Debug mode, displaying topic classification and scraping strategy.
*   **Fix**: Optimized injection logic, precisely positioning to the right of nickname, excluding avatar interference.
*   **Fix**: Fixed issue where citation links were in API format, unified to web links.

### v0.1.0 (2024-01-02) - MVP Release
*   **Feature**: Completed basic architecture (Plasmo + React + TypeScript).
*   **Feature**: Implemented Zhihu API scraping and cleaning.
*   **Feature**: Connected OpenAI/Gemini/Ollama interfaces.
*   **Feature**: Implemented basic UI injection and profile display card.
*   **Feature**: Supports API Key configuration.

`;

// DeepProfile Version History
export const enUSVersionHistory = `# DeepProfile Version History

### Memory Optimization (v0.8.1) - Memory Management & Leak Fixes
- ✅ **Memory Leak Fixes**: Fixed memory leaks caused by timers not being properly cleared in the background service
- ✅ **Event Listener Management**: Improved registration and deregistration mechanisms for event listeners in content scripts to prevent duplicate bindings
- ✅ **Cache Strategy Optimization**: Optimized cache cleanup mechanisms for history records, regularly cleaning up expired data
- ✅ **Component Unmount Optimization**: Improved unmount logic for React components to ensure DOM nodes and event handlers are properly cleaned up
- ✅ **Resource Management**: Added tracking for active timers to prevent timer accumulation

### Core Feature (v0.8.0) - Platform Expansion & UI Modernization
- ✅ **Quora Platform Support**: Added user profile analysis support for Quora platform, including content scraping and user info extraction
- ✅ **Twitter/X Platform Support**: Added user profile analysis support for Twitter/X platform, adapting to new API interfaces
- ✅ **UI Modernization**: Adopted modern UI design, updated settings page layout with card-based design for improved visual experience
- ✅ **Icon Updates**: Added dedicated icons for all supported platforms, enhancing interface aesthetics
- ✅ **Responsive Enhancement**: Optimized interface display across different screen sizes

### Core Feature (v0.7.1) - Label Display & LLM Output Optimization
- ✅ **Label Display Fix**: Resolved issues where certain labels (e.g., \`competition_vs_equality\`, \`speculation_vs_value\`) were not displaying correctly in the frontend.
- ✅ **Label Definition Sync**: Ensured label definitions in \`LabelService\` are fully synchronized with \`LabelDefinitions\`, eliminating display errors caused by ID mismatches.
- ✅ **LLM Output Standardization**: Added automatic standardization for LLM-returned label IDs, capable of correcting non-standard label IDs (e.g., mapping \`nationalism_globalism\` to \`geopolitics\`).
- ✅ **Duplicate Label Handling**: Optimized result parsing logic to automatically merge and deduplicate labels returned by LLM, prioritizing scores with higher confidence.

### Core Feature (v0.7.0) - Improved Profile Analysis Accuracy & Consistency
- ✅ **AI Summary Consistency**: Ensure AI-generated summaries are consistent with numerical label scores
- ✅ **Consistency Verification Mechanism**: Added ConsistencyService to verify and fix summary-label consistency
- ✅ **Label-Summary Association**: High-scoring labels are clearly reflected in summaries
- ✅ **Evidence Support**: Ensure analysis evidence matches label scores

### Core Feature (v0.6.3) - Analysis Progress Visualization & Label Display Optimization
- ✅ **Progress Estimation**: Show estimated remaining time based on analysis mode (e.g., "Analyzing... (15s)")
- ✅ **Progress Bar Animation**: Display dynamic progress bar for intuitive analysis progress indication.
- ✅ **Mode Differentiation**: Different analysis modes (Fast/Balanced/Deep) show different estimated times.
- ✅ **Bidirectional Divergent Bar Chart Optimization**: Value labels are left-right aligned, with percentages displayed above bidirectional divergent bars.

### v0.6.2 (2024-01-09) - Theme System
*   **Feature**: **Theme Customization**, supports user-defined appearance themes, including color schemes, fonts, sizes, etc.
*   **Feature**: **Multiple Built-in Themes**, provides multiple preset themes, including Zhihu White/Black themes, Reddit White/Black themes.
*   **Feature**: **Dynamic Theme Switching**, supports real-time theme switching without refreshing the page.
*   **Feature**: **CSS Variable Driven**, uses CSS variables to implement global theme dynamic application, ensuring all components update synchronously.
*   **Feature**: **Theme Management**, supports creating, editing, deleting custom themes, and provides theme import/export functionality.

### v0.6.1 (2024-01-09) - Real-time Settings Save
*   **Feature**: Implemented **real-time settings save functionality** on the settings page, all configuration changes are immediately saved to storage automatically.
*   **Feature**: Removed manual save button, simplifying the settings interface.
*   **Feature**: Configuration changes take effect immediately without restart or refresh.
*   **UX**: Improved user experience with a smoother settings workflow.

### v0.6.0 (2024-01-08) - Reddit Platform Multilingual Support Enhancement
*   **Feature**: Fixed I18nService initialization issue on Reddit platform to ensure multilingual functionality works properly.
*   **Feature**: Refactored button injection logic on Reddit platform to align with Zhihu platform, resolving the disappearing button issue.
*   **Feature**: Ensured that Reddit platform analysis buttons and user profile cards support Chinese/English interface switching.
*   **Feature**: Implemented consistent button injection mechanism aligned with Zhihu platform, including configuration checks, cleanup functions, and orphaned button removal features.
*   **Feature**: Updated internationalization support for loading, analysis, and error status messages to ensure interface fully follows user language settings.

### v0.5.0 (2024-01-07) - Reddit Platform Support
*   **Feature**: **Reddit Platform Support**, added support for analyzing Reddit user profiles.
*   **Feature**: **Cross-Platform Architecture**, refactored code to support multi-social platform expansion.
*   **Feature**: **Platform-Specific Configuration**, allows setting different analysis parameters for different platforms.
*   **Feature**: **Reddit Content Scraping**, implemented content extraction and parsing for Reddit API.
*   **Feature**: **Platform-Specific UI**, adapted user interface styles for Reddit.

### v0.4.0 (2024-01-06) - Comment Analysis Feature
*   **Feature**: **Comment Analysis**, added specialized comment analysis feature to analyze user comments under specific posts.
*   **Feature**: **Sentiment Analysis**, implemented emotional tendency analysis of user comments (support/oppose/neutral).
*   **Feature**: **Opinion Clustering**, automatically clusters main opinions in user comments.
*   **Feature**: **Position Identification**, identifies user positions on controversial topics.
*   **Feature**: **Public Opinion Overview**, generates AI summary of overall public opinion.

### v0.3.0 (2024-01-05) - Value Label System
*   **Feature**: **Value Label System**, established multi-dimensional value orientation label system (political, economic, social, cultural, technological, etc.).
*   **Feature**: **Quantitative Analysis**, transforms value orientations into quantitative scores between -1 and 1.
*   **Feature**: **Bipolar Coordinates**, uses bipolar coordinate system to intuitively display value orientations.
*   **Feature**: **Label Visualization**, displays value distributions in various dimensions through chart form.
*   **Feature**: **Label Explanations**, provides detailed explanations for each label.

### v0.2.1 (2024-01-04) - Optimization & Fixes
*   **Fix**: Optimized content scraping logic, added handling for API rate limiting.
*   **Fix**: Fixed issues where analysis results were incomplete in certain situations.
*   **Fix**: Improved error handling mechanisms, providing clearer error messages.
*   **UI**: Fine-tuned UI component styles, enhancing visual effects.
*   **Performance**: Optimized caching mechanisms, improving response speed for repeated queries.

### v0.2.0 (2024-01-03) - Deep Analysis and Context Awareness
*   **Feature**: Added context-aware functionality, automatically filtering user's relevant answers based on current browsing question.
*   **Feature**: Added "Analysis Mode" setting (Fast/Balanced/Deep), Deep mode supports irony identification.
*   **Feature**: Profile labels added confidence probability display.
*   **Feature**: Enhanced Debug mode, displaying topic classification and scraping strategy.
*   **Fix**: Optimized injection logic, precisely positioning to the right of nickname, excluding avatar interference.
*   **Fix**: Fixed issue where citation links were in API format, unified to web links.

### v0.1.0 (2024-01-02) - MVP Release
*   **Feature**: Completed basic architecture (Plasmo + React + TypeScript).
*   **Feature**: Implemented Zhihu API scraping and cleaning.
*   **Feature**: Connected OpenAI/Gemini/Ollama interfaces.
*   **Feature**: Implemented basic UI injection and profile display card.
*   **Feature**: Supports API Key configuration.
`;