import type { LocaleDict } from "./index";

export const enUS: LocaleDict = {
  // General
  app_name: "DeepProfile",
  app_description: "AI-powered User Profile Analysis Tool",
  loading: "Loading...",
  save: "Settings Saved",
  saved: "Saved!",
  cancel: "Cancel",
  delete: "Delete",
  confirm_delete: "Are you sure?",
  clear_all: "Clear All",
  confirm_clear_all: "Are you sure you want to clear all history? This action cannot be undone.",
  export_markdown: "Export as Markdown",
  export_image: "Export as Image",
  export_image_failed: "Export as Image Failed",
  settings: "Settings Menu",

  // Options Page
  settings_general: "General Settings",
  settings_zhihu: "Zhihu Settings",
  settings_reddit: "Reddit Settings",
  debug_mode: "Debug Mode",
  debug_mode_desc: "Enable detailed logging",
  settings_history: "History",
  settings_debug: "Developer Options",
  plugin_enabled: "✅ Plugin Enabled",
  plugin_disabled: "⛔ Plugin Disabled",
  plugin_enabled_desc: "DeepProfile is working normally and will display analysis buttons on target websites.",
  plugin_disabled_desc: "DeepProfile is completely turned off and will not inject code into any website.",
  ai_provider: "AI Provider",
  api_key: "API Key",
  api_base_url: "API Base URL",
  model_select: "Model Selection",
  test_connection: "🔌 Test Connection",
  connection_success: "✅ Connection Successful",
  connection_failed: "❌ Connection Failed",
  analysis_mode: "Analysis Mode",
  analyze_limit: "Number of Answers to Analyze",
  mode_fast: "⚡ Fast",
  mode_balanced: "⚖️ Balanced",
  mode_deep: "🧠 Deep",
  mode_fast_desc: "Minimal content, fastest analysis",
  mode_balanced_desc: "Moderate content, balanced speed and quality",
  mode_deep_desc: "Maximum content, most comprehensive analysis",
  
  // Categories
  category_politics: "🏛️ Politics",
  category_economy: "💰 Economy",
  category_society: "👥 Society",
  category_technology: "💻 Technology",
  category_culture: "🎨 Culture",
  category_environment: "🌍 Environment",
  category_entertainment: "🎮 Entertainment",
  category_lifestyle_career: "💼 Lifestyle & Career",
  category_general: "🌐 General",
  
  // Profile Card
  analyzing: "Analyzing",
  topic_classification: "Topic Classification",
  value_orientation: "Value Orientation",
  ai_summary: "AI Summary",
  evidence: "Evidence",
  source: "Source",
  expand: "Expand",
  collapse: "Collapse",
  reanalyze: "Re-analyze",
  wait_moment: "Please wait a moment...",
  history_record: "History Record",
  history_empty: "No history records",
  total_users_max: "Total {count} users (Max {max})",
  debug_info: "Debug Info",
  token_usage: "Model",
  total_duration: "Total Duration",
  llm_duration: "AI Duration",
  data_items: "Data Items",
  data_breakdown: "Data Breakdown",
  unknown_user: "Unknown User",
  unknown_topic: "Unknown Topic",
  
  // Errors
  error_401: "Authentication Failed (401) 🔐: Please check if your API Key is correct.",
  error_402: "Insufficient Balance (402) 💸: Please check your API Key balance.",
  error_404: "Model Not Found (404) 🗺️: Please check your model configuration.",
  error_429: "Too Many Requests (429) 🔥: AI is busy, please try again later.",
  error_500: "AI Provider Error (500) 💥: Please try again later.",
  error_network: "Network Error 🌐: Please check your internet connection or proxy settings.",
  error_zhihu_403: "Access Denied by Zhihu (403) 🚧. Please try refreshing the page or logging in.",
  error_user_not_found: "User data not found 🕵️‍♂️. The account might be banned or set to private.",

  // Export
  click_jump: "Click to Jump",
  no_data: "No data available",
  generated_by: "Generated by",
  scan_to_install: "Scan to install",
  start_ai_journey: "Start your AI journey",
  ai_profile_analysis: "AI-powered User Profile Analysis",
  date_label: "Date",
  
  // Comment Analysis
  analyzing_comments: "Analyzing comments on current page...",
  expanding_comments: "Expanding comment section...",
  extracting_comments: "Extracting comment data...",
  ai_reading: "AI is reading everyone's opinions...",
  comment_analysis_failed: "Analysis failed",

  // Theme Settings
  theme_settings: "Theme Settings",
  select_theme: "Select Theme",
  create_custom_theme: "Create Custom Theme",
  theme_id: "Theme ID",
  theme_name: "Theme Name",
  theme_description: "Theme Description",
  unique_theme_identifier: "Unique theme identifier",
  display_name_for_theme: "Display name for the theme",
  optional_description: "Optional description for the theme",
  create_theme: "Create Theme",
  theme_created: "Theme created successfully!",
  theme_updated: "Theme updated successfully!",
  theme_deleted: "Theme deleted successfully!",
  theme_applied: "Theme applied successfully!",
  theme_zhihu_white_name: "Zhihu White Theme",
  theme_zhihu_white_desc: "Zhihu-inspired light theme with blue accents",
  theme_zhihu_black_name: "Zhihu Dark Theme",
  theme_zhihu_black_desc: "Zhihu-inspired dark theme with blue accents",
  theme_reddit_white_name: "Reddit White Theme",
  theme_reddit_white_desc: "Reddit-inspired light theme with orange-blue accents",
  theme_reddit_black_name: "Reddit Dark Theme",
  theme_reddit_black_desc: "Reddit-inspired dark theme with orange-blue accents",
  failed_load_themes: "Failed to load themes",
  failed_apply_theme: "Failed to apply theme",
  failed_create_theme: "Failed to create theme",
  failed_delete_theme: "Failed to delete theme",
  failed_save_theme: "Failed to save theme",
  theme_id_name_required: "Please enter theme ID and name",
  cannot_delete_builtin_theme: "Cannot delete built-in themes",
  confirm_delete_theme: "Are you sure you want to delete this theme? This action cannot be undone.",
  edit: "Edit",
  color_settings: "Color Settings",
  color_primary: "Primary Color",
  color_secondary: "Secondary Color",
  color_background: "Background Color",
  color_surface: "Surface Color",
  color_text: "Text Color",
  color_textSecondary: "Secondary Text Color",
  color_border: "Border Color",
  color_success: "Success Color",
  color_warning: "Warning Color",
  color_error: "Error Color",
  color_accent: "Accent Color",
  save_changes: "Save Changes",
  
  // Context Invalidated Error
  extension_context_invalidated: "Extension context invalidated",
  extension_context_invalidated_title: "Extension Context Invalidated",
  extension_context_invalidated_desc: "Extension context has been invalidated. Please refresh the page to retry.",
  
  // Version Info
  version_info: "Version Information",
  current_version: "Current Version",
  changelog: "Changelog",
  version_history: "Version History",
  
  // Comment Analysis
  comment_summary_btn: "Analyze Comments",
  anonymous_user: "Anonymous User",
  not_enough_comments: "Not enough comments for analysis",
  comment_analysis_instruction: ", please try increasing the number of comments displayed.",
  comment_analysis_summary: "Comment Analysis Summary",
  comment_analysis_ai_generated: "AI Generated",
  sentiment_support: "Support",
  sentiment_neutral: "Neutral",
  sentiment_oppose: "Oppose",
  expand_key_points: "Expand Key Points",
  collapse_key_points: "Collapse Key Points",
  deep_insight: "Deep Insight",
  logic_fallacy: "Logical Fallacy Detected",
  unknown_type: "Unknown Type",
  example_quote: "Example Quote",
  
  // Reddit Overlay
  deep_profile_analysis: "Deep Profile Analysis"
};

// DeepProfile Development Progress and Changelog
export const enUSChangelog = `# DeepProfile Development Progress and Changelog

## Current Version: v0.6.1 (Beta)

### ✅ Features Achieved

### Core Feature (v0.6.1) - Real-time Settings Save
- ✅ **Real-time Save**: All settings changes (language, API keys, analysis modes, etc.) are **immediately saved automatically**, no save button required.
- ✅ **Instant Application**: Configuration changes take effect immediately in the extension functionality, no restart or refresh needed.
- ✅ **UX Optimization**: Removed manual save button, simplifying the settings workflow for a smoother user experience.

### Core Feature (v0.5.1) - Multi-language Support (i18n)
- ✅ **Internationalization Architecture**: Introduced a lightweight \`I18nService\` for dynamic language switching.
- ✅ **Bilingual Interface**: Full support for **Simplified Chinese (zh-CN)** and **English (en-US)**.
    - Options Page
    - Profile Card Overlay
    - Error messages and status feedback
- ✅ **Bilingual AI Analysis**: 
    - Optimized prompt engineering to force AI output in the selected language.
    - The label system supports bilingual display (e.g., "左派 vs 右派" / "Left vs Right").
- ✅ **Dynamic Switching**: The interface updates instantly after changing the language in the settings, no restart required.

### Core Feature (v0.5.0) - Comment Sentiment Summary
- ✅ **Sentiment Overview**: Added a "📊 Summarize Page Views" button at the top of Zhihu comments section to generate an overview of current page's sentiment with one click.
- ✅ **Zero-risk Analysis**: Only analyzes loaded comment text on current page, **does not call Zhihu API**, completely avoiding risk control and account blocking.
- ✅ **Position Distribution**: Automatically calculates the proportion of supporters, opponents, and neutral observers, displaying with visual progress bars.
- ✅ **Core Points Extraction**: Intelligently summarizes 3-5 recurring core arguments in the comments section, with typical comment excerpts attached.
- ✅ **Emotion Detection**: Automatically determines the comment section atmosphere (positive/negative/highly controversial).

### Core Feature (v0.4.2) - Enhanced Export Functionality and UX Optimization
- ✅ **Image Export Upgrade**:
    - **Personalized Avatar**: Exported profile cards now display the user's **Zhihu avatar**, not the default plugin logo.
    - **QR Code Sharing**: Added QR code pointing to Chrome Web Store at the bottom of card for easy sharing and distribution.
    - **Technical Breakthrough**: Solved \`html2canvas\` cross-origin image rendering issues, ensuring stable avatar display.
- ✅ **Enhanced History Records**:
    - **Full Function Export**: Added "📸 Export as Image" button to each record in the background history management.
    - **Display Fix**: Fixed the issue where user nicknames were displayed as IDs in history records, now prioritizing display of user nicknames.
- ✅ **Error Prompt Optimization**:
    - **Plain Language Translation**: Replaced boring HTTP error codes (401, 402, 429, etc.) with witty, easy-to-understand Chinese prompts (such as "Wallet Empty", "Wrong Password").
    - **403 Guidance**: Added friendly prompts guiding users to refresh the page or log in for Zhihu API 403 errors.
- ✅ **UI Details**:
    - Added user avatar display to the header of the analysis result overlay card.

### Core Feature (v0.4.1) - Performance Optimization and Prompt Simplification
- ✅ **Dynamic Prompt Trimming**: 
    - **On-demand Loading**: Based on current topic category (e.g. "Technology"), only send relevant label definitions under that category to LLM, instead of sending all labels.
    - **Token Savings**: System Prompt length reduced by approximately 60%, significantly reducing Token consumption and improving response speed.
    - **Improved Focus**: Reduces interference from irrelevant labels, allowing LLM to focus more on current domain analysis.
- ✅ **Label System Optimization**:
    - Refactored \`LabelService\` to support fetching label definitions by category.
    - Optimized \`TopicService\` to improve keyword matching accuracy.

### Core Feature (v0.4.0) - History Record and Cache System
- ✅ **Local Cache Mechanism**: 
    - Automatically stores generated user profiles locally (\`chrome.storage.local\`).
    - Uses **"User Aggregation + Domain Layering"** storage structure, ensuring that a user's profiles in different domains (e.g. politics, entertainment) do not interfere with each other.
    - Default cache validity is 24 hours, expiring automatically.
- ✅ **Smart Cache Hit**: 
    - **Second-level Response**: When revisiting an analyzed user, directly load results from cache without waiting for API requests.
    - **Zero Token Consumption**: Does not call LLM interface when cache hits, saving costs.
    - **Domain Adaptation**: Automatically recognizes current topic domain, prioritizing loading of historical profiles in that domain.
- ✅ **History Record Management**:
    - Added "History Records" panel to settings page.
    - Supports viewing list of all analyzed users (sorted by time).
    - Supports expanding to view detailed domain profiles for each user (politics, economy, entertainment, etc.).
    - Supports fine-grained deletion (single profile, single user) or one-click clearing.
- ✅ **Force Refresh**:
    - Added "Re-analyze" button to analysis result card, allowing users to ignore cache and force update.

### Core Feature (v0.3.0)
- ✅ **Multi-platform Architecture**: Reserved extension interfaces for multi-platform support such as Reddit.
- ✅ **Multi-model Support**:
    - Added **Qwen (Tongyi Qianwen)** and **Custom (OpenAI Compatible)** service providers.
    - Supports **dynamic loading of model list**, avoiding manual input errors.
- ✅ **Zhihu Data Scraping**: 
    - Automatically parses user Hash ID to URL Token.
    - **Hybrid Data Sources**: Parallel scraping of user's **original content (answers/articles)** and **endorsement activities**.
    - Supports scraping quantity configuration (10-50 items).
- ✅ **Context-aware**:
    - **Precise Extraction**: Automatically extracts current page's question title and **official Zhihu topic tags**.
    - **Intelligent Classification**: Introduced **TopicService**, automatically classifying topics into eight major macro domains such as "politics", "economy", "technology", etc.
    - **Hybrid Classification Strategy**: Prioritizes keyword matching, automatically degrading to LLM intelligent classification when matching fails.
- ✅ **Deep Profile Generation**:
    - **Content First**: Prioritizes extraction and analysis of **answer/article body**, not brief summaries.
    - **Risk Control**: Changed "political orientation" to "value orientation", conducting neutral analysis from multiple dimensions such as "economics", "culture", "international perspective", etc.
    - **Contradiction Analysis**: Requires LLM to explain contradictions in user opinions in the summary.
    - **Evidence Citation**: Provides clickable original citation links, supporting navigation to specific answers/articles.

### User Experience (UI/UX)
- ✅ **Seamless Injection**: Only displays "🔍" icon to the right of user nickname, automatically filtering avatars and duplicate links.
- ✅ **Real-time Feedback**: 
    - Click to display user nickname.
    - Detailed progress prompts (fetching information -> scraping dynamics -> AI analysis).
- ✅ **Result Display**:
    - **Multi-dimensional Value Map**: Uses progress bars to display value orientations across different dimensions.
    - Collapsible evidence panel, maintaining interface tidiness.
- ✅ **Connection Test**: Provides "Test Connection" function on settings page, returning **friendly Chinese error prompts** (such as insufficient balance, invalid key).

### Advanced Settings
- ✅ **Custom Configuration**:
    - **Model Dropdown Selection**: Automatically acquires and displays available model list.
    - Custom API Base URL (supports proxy).
- ✅ **Analysis Mode**:
    - **⚡ Fast**: Quick overview.
    - **⚖️ Balanced**: Standard analysis.
    - **🧠 Deep**: Enables Chain of Thought (CoT), deep identification of irony and metaphor.
- ✅ **Developer Debug (Debug Mode)**:
    - **Transparency**: Added \`Source\` field, clearly showing "how many fetched -> how many found relevant -> how many finally analyzed".
    - **Data Tracing**: Added \`Breakdown\` field, showing original content vs endorsement content ratio.

---

## Version History

### v0.6.1 (2024-01-09) - Real-time Settings Save
*   **Feature**: Implemented **real-time settings save functionality** on the settings page, all configuration changes are immediately saved to storage automatically.
*   **Feature**: Removed manual save button, simplifying the settings interface.
*   **Feature**: Configuration changes take effect immediately without restart or refresh.
*   **UX**: Improved user experience with a smoother settings workflow.

### v0.6.0 (2024-01-08) - Reddit Platform Multilingual Support Enhancement
*   **Feature**: Fixed I18nService initialization issue on Reddit platform to ensure multilingual functionality works properly.
*   **Feature**: Refactored button injection logic on Reddit platform to align with Zhihu platform, resolving the disappearing button issue.
*   **Feature**: Ensured that Reddit platform analysis buttons and user profile cards support Chinese/English interface switching.
*   **Feature**: Implemented consistent button injection mechanism aligned with Zhihu platform, including configuration checks, cleanup functions, and orphaned button removal features.
*   **Feature**: Updated internationalization support for loading, analysis, and error status messages to ensure interface fully follows user language settings.
*   **Feature**: Fixed useCallback import issue in Reddit overlay, optimizing component performance.

### v0.5.1 (2024-01-10) - Multi-language Support
*   **Major Feature**: Full support for **Simplified Chinese** and **English** bilingual switching.
*   **Feature**: AI analysis results automatically adapt to selected language.
*   **Refactor**: Introduced \`I18nService\` to manage text resources uniformly.

### v0.5.0 (2024-01-09) - Comment Sentiment Summary
*   **Major Feature**: **Comment Sentiment Summary**, one-click generation of page sentiment profile, including position distribution, core views, and emotion detection.
*   **Security**: Adopted **zero-risk analysis** strategy, only analyzing loaded DOM text, not calling Zhihu API, completely avoiding risk control.

### v0.4.2 (2024-01-08) - Enhanced Export and UX Optimization
*   **Feature**: Export images support displaying user avatars and QR codes.
*   **Feature**: History record management supports image export.
*   **Fix**: Fixed user nickname display issue in history records.
*   **Fix**: Optimized Zhihu API request headers, resolving 403 issue.
*   **UX**: Error prompt copy optimized, more friendly and witty.

### v0.4.1 (2024-01-07) - Performance Optimization
*   **Optimization**: **Dynamic Prompt Trimming**, based on topic category only loads relevant label definitions, significantly reducing Token consumption and improving response speed.
*   **Refactor**: Optimized label service and topic service, improving code maintainability.

### v0.4.0 (2024-01-06) - History Records and Intelligent Classification
*   **Major Feature**: **History Record System**, supporting local cache, second-level response, and visual management.
*   **Major Feature**: **Eight-dimensional Full Spectrum Classification**, introducing 30+ sub-dimensions in politics, economy, society, technology, etc., making profiles more three-dimensional.
*   **Feature**: **Hybrid Classification Strategy**, combining keyword matching with LLM intelligent classification, ensuring accurate topic categorization.
*   **Feature**: **Domain Adaptive Analysis**, LLM automatically judges content relevance, avoiding incorrect analysis due to topic mismatch.
*   **Optimization**: **Deep Prompt Desensitization**, significantly reducing probability of triggering content security risk control.
*   **UI**: Added "History Records" panel to settings page, supporting expansion view and fine-grained management.

### v0.3.0 (2024-01-04) - Precise Focus and UX Optimization
*   **Major Feature**: **Refactored Context-aware Algorithm**, using topic tags for precise matching and adopting dynamic truncation strategy, completely solving topic deviation issues.
*   **Major Feature**: **Refactored Prompt**, using "value orientation" instead of "political orientation", avoiding domestic model risk control, and requiring AI to explain contradiction points.
*   **Feature**: **New "Connection Test" Function**, providing friendly Chinese error prompts.
*   **Feature**: **Dynamic Model List Loading**, upgraded model name input box to dropdown selection box.
*   **Feature**: Added support for **Qwen (Tongyi Qianwen)** and **Custom OpenAI Compatible Interface**.
*   **Feature**: Data source adds **user like activity**, and can display source ratio in Debug panel.
*   **Fix**: Prioritizes extracting and analyzing **complete body** of answers/articles, not brief summaries.
*   **UI**: Modernized settings page UI, adopting card-based layout.

### v0.2.0 (2024-01-03) - Deep Analysis and Context Awareness
*   **Feature**: Added context-aware functionality, automatically filtering user's relevant answers based on current browsing question.
*   **Feature**: Added "Analysis Mode" setting (Fast/Balanced/Deep), Deep mode supports irony identification.
*   **Feature**: Profile labels added confidence probability display.
*   **Feature**: Enhanced Debug mode, displaying topic classification and scraping strategy.
*   **Fix**: Optimized injection logic, precisely positioning to the right of nickname, excluding avatar interference.
*   **Fix**: Fixed issue where citation links were in API format, unified to web links.

### v0.1.0 (2024-01-02) - MVP Release
*   **Feature**: Completed basic architecture (Plasmo + React + TypeScript).
*   **Feature**: Implemented Zhihu API scraping and cleaning.
*   **Feature**: Connected OpenAI/Gemini/Ollama interfaces.
*   **Feature**: Implemented basic UI injection and profile display card.
*   **Feature**: Supports API Key configuration.

---

## 📅 Roadmap

- ✅ **v0.6.2 Theme Feature**: Implement customizable overlay styling, allowing users to customize appearance themes including color schemes, fonts, sizes, etc. (Completed)
- [ ] **More Platforms**: Explore support for Reddit, Bilibili, Weibo, and other platforms.
`;